In [1]:
import pandas as pd

In [2]:
s=pd.read_csv("dataset_study.csv")
s

,student_id,study_hours,grade
0,1,9.15,91.91
1,2,9.37,86.81
2,3,2.86,53.39
3,4,8.30,85.52
4,5,6.42,77.98
...,...,...,...
4995,4996,4.89,58.91
4996,4997,4.43,65.22
4997,4998,9.91,81.11
4998,4999,6.91,73.79


In [3]:
s=s.drop("student_id",axis="columns")
s

,study_hours,grade
0,9.15,91.91
1,9.37,86.81
2,2.86,53.39
3,8.30,85.52
4,6.42,77.98
...,...,...
4995,4.89,58.91
4996,4.43,65.22
4997,9.91,81.11
4998,6.91,73.79


In [4]:
s.isnull().sum()

study_hours    0
grade          0
dtype: int64

In [5]:
#data exploration
s.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   study_hours  5000 non-null   float64
 1   grade        5000 non-null   float64
dtypes: float64(2)
memory usage: 78.3 KB


In [6]:
s.describe()

,study_hours,grade
count,5000.000000,5000.000000
mean,5.031654,64.969712
std,2.910579,17.657329
min,0.000000,15.520000
25%,2.520000,51.717500
50%,5.050000,64.975000
75%,7.582500,78.710000
max,10.000000,100.000000


In [7]:
#feature engineering
import numpy as np
x=s[["study_hours"]]
y=s["grade"]
x

,study_hours
0,9.15
1,9.37
2,2.86
3,8.30
4,6.42
...,...
4995,4.89
4996,4.43
4997,9.91
4998,6.91


In [8]:
y

0       91.91
1       86.81
2       53.39
3       85.52
4       77.98
        ...  
4995    58.91
4996    65.22
4997    81.11
4998    73.79
4999    55.08
Name: grade, Length: 5000, dtype: float64

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=42)
x_train

,study_hours
3716,5.55
3779,3.49
135,5.80
4480,8.87
1437,9.58
...,...
4426,7.85
466,3.21
3092,3.37
3772,0.31


In [10]:
x_test

,study_hours
1501,9.55
2586,6.22
2653,9.34
1055,8.23
705,7.06
...,...
3928,4.47
544,5.63
367,9.25
1612,3.25


In [11]:
from sklearn.preprocessing import StandardScaler
k=StandardScaler()
kx_train=k.fit_transform(x_train)
kx_train

array([[ 0.18152883],
       [-0.52657455],
       [ 0.26746371],
       ...,
       [-0.56782329],
       [-1.61966618],
       [ 1.63554694]])

In [12]:
kx_test=k.transform(x_test)
kx_test

array([[ 1.55648686e+00],
       [ 4.11834302e-01],
       [ 1.48430156e+00],
       [ 1.10275071e+00],
       [ 7.00575488e-01],
       [ 8.17446920e-01],
       [ 7.31512043e-01],
       [-1.62210673e-01],
       [-1.27836722e-01],
       [ 8.69007846e-01],
       [ 6.79951117e-01],
       [-1.56123046e+00],
       [ 8.79320031e-01],
       [ 3.19024636e-01],
       [ 4.74704258e-02],
       [-1.62997836e+00],
       [ 1.53586249e+00],
       [-1.03874641e+00],
       [ 2.22777574e-01],
       [ 6.90263302e-01],
       [-1.24842751e+00],
       [-1.55779307e+00],
       [ 9.99628858e-01],
       [ 2.50276734e-01],
       [ 3.25899426e-01],
       [-1.11780650e+00],
       [-5.30011945e-01],
       [-3.54704796e-01],
       [-5.19699759e-01],
       [ 1.34680576e+00],
       [-5.30011945e-01],
       [-9.35624562e-01],
       [ 4.32458673e-01],
       [-1.47529559e+00],
       [-1.01468465e+00],
       [-5.36886735e-01],
       [ 6.93700698e-01],
       [-4.30327488e-01],
       [ 1.0

In [13]:
from sklearn.linear_model import Ridge

ridge = Ridge(alpha=1.0)
ridge.fit(kx_train, y_train)

print("R²:", ridge.score(kx_test, y_test))


R²: 0.6948262112781812


In [14]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [15]:
y_pred=lr.predict(x_test)
y_pred

array([87.59143866, 70.9696744 , 86.54321929, 81.0026312 , 75.16255187,
       76.85966894, 75.61178874, 62.63383467, 63.13298675, 77.60839706,
       74.86306062, 42.31834502, 77.75814269, 69.62196379, 65.67866236,
       41.32004086, 87.29194741, 49.90545664, 68.22433796, 75.01280625,
       46.86062895, 42.36826023, 79.50517496, 68.62365963, 69.7217942 ,
       48.75740685, 57.29290742, 59.83858302, 57.44265304, 84.54661097,
       57.29290742, 51.40291287, 71.26916565, 43.56622522, 50.25486309,
       57.193077  , 75.06272145, 58.74044845, 80.55339433, 64.7302734 ,
       85.04576305, 49.60596539, 81.65152891, 49.35638935, 86.6430497 ,
       52.55096266, 46.21173125, 79.25559892, 67.2260338 , 88.24033636,
       71.31908086, 53.84875807, 73.41551959, 63.73196924, 48.70749164,
       62.13468259, 43.56622522, 45.71257917, 46.41139208, 64.33095174,
       64.43078216, 74.41382375, 62.13468259, 48.4579156 , 87.19211699,
       87.19211699, 86.39347366, 52.85045391, 73.21585876, 85.44

In [16]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.6948382641132321